name: dlp_officer
description: DLP for stuff

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.1.0

  shared_preferences: ^0.5.6+1

  json_serializable: ^3.2.5

  http: ^0.12.0+4
  http_interceptor: ^0.2.0

  rxdart: ^0.23.1

  bloc: ^3.0.0
  flutter_bloc: ^3.2.0

  flutter_svg: ^0.17.1

  cupertino_icons: ^0.1.2

  inject:
    path: ./vendor/inject.dart/package/inject

dev_dependencies:
  flutter_test:
    sdk: flutter

  inject_generator:
    path: ./vendor/inject.dart/package/inject_generator

  build_runner: ^1.7.4

flutter:
  uses-material-design: true
